### ISSUE TITLE
Consider alternative formats for documenting config parameters 

### ISSUE THREAD

**Issue by iffyio** [googleforgames/quilkin#149]
Currently, we're using yaml schema which could be quite noisy and more difficult to read, when there are a large number of parameters.
Maybe https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#job might be a better alternative? it's not as precise but its simpler to read at least. Or something else?

_Originally posted by @iffyio in https://github.com/googleforgames/quilkin/pull/144#discussion_r530548893_

**Comment by XAMPPRocky** [comment]
I think we're sufficiently documenting the configuration in enough different ways, both in JSON schema and in the Rust documentation.
