### ISSUE TITLE
Alternatives to proto submodules

### ISSUE THREAD

**Issue by iffyio** [googleforgames/quilkin#169]
Thinking rather than managing submodules, it might make sense to generate the grpc files once and check that in instead?

**Comment by markmandel** [comment]
Seems like this is working. Shall we close this now, at least until we hit a pain point that means we should reopen/create a new issue?

**Comment by XAMPPRocky** [comment]
Yeah, this is mostly fine, don't much run into sub modules issues since we don't really touch them often enough for them to come up.
