### ISSUE TITLE
review metrics to prevent high-cardinality data

### ISSUE THREAD

**Issue by jahrlin** [googleforgames/quilkin#263]
We want to make sure that Quilkin metrics do not contain high cardinality data, to avoid "cardinality bombs".

an example I found was the metric `quilkin_session_tx_packets_total`, which has labels for `downstream` and `upstream`.

If the instance is running on the edge (not behind an LB) the number of possible values for `downstream` could be any number, which can result in metrics like these:

```
quilkin_session_tx_packets_total{downstream="1.1.1.1:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.2:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.3:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.4:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.5:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.6:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.7:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.8:12345", upstream="10.1.1.2:12345"}
quilkin_session_tx_packets_total{downstream="1.1.1.9:12345", upstream="10.1.1.2:12345"}
.................. repeat many many times
quilkin_session_tx_packets_total{downstream="255.255.255.255:12345", upstream="10.1.1.2:12345"}
```

eventually Quilkin would run out of memory simply from keeping track of all these series, but it also means Quilkin could cause problems for operators such as cost spikes for managed Prometheus solutions and memory inflation in Prometheus.

we should review possible label values and probably write some documentation on what to keep in mind regarding metrics

**Comment by iffyio** [comment]
Closing this since we've removed the high cardinality metrics
