### ISSUE TITLE
[bot] Hide Old Comment On Push

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#266]
Also would be nice if the GitHub bot hid its previous comment when you push to a PR.

_Originally posted by @XAMPPRocky in https://github.com/googleforgames/quilkin/issues/264#issuecomment-844248568_

**Comment by markmandel** [comment]
Since it came up on Discord, here is where the bot code is:

https://github.com/googleforgames/quilkin/tree/main/build/ci/github-bot

**Comment by markmandel** [comment]
So I'm pretty happy with how the bot is working with deleting old statuses! I've yet to want go back to a previous build.

So unless anyone objects, I'm happy to close this ticket!
