### ISSUE TITLE
Message queues should drop when full

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#380]
When going through the code with @luna-duclos yesterday, we noticed that currently we're using bounded queues that will block when full, when ideally we should be dropping some or all of the messages in the receiver when the limit is hit. This will probably require either creating a new queue type or finding a library with this behaviour.

**Comment by markmandel** [comment]
Very late to the party, but have had this ticket rolling around my head, and have been meaning to write something for a while.

I'd love to come at this from a problem first type approach:

I.e.
1. What are the different scenarios in which a proxy could be overwhelmed? (ddos? bad config? can we tell the difference?)
2. When it does get overwhelmed, what are the solutions that could solve this? (rate limiting, dropping packets, monitoring, rules and actions? etc)
3. Do each of the solutions work in all scenarios? Do they work for all users? Should they be configurable? If so, how?

Then we can weigh the tradeoffs of each solution comparatively, and start making some design decisions.

(Sounds like a good topic for the next community meeting 👍🏻)

**Comment by markmandel** [comment]
Action item from community meeting: Let's test overloading the proxy and record what exactly happens 👍🏻

**Comment by XAMPPRocky** [comment]
To add to that, as an initial goal, I think we only initially care about what happens in the docker container version of Quilkin, since that's what we're deploying right now. The behaviour when running on a Mac or Windows or even desktop is a bit less of a concern than the containerised version IMO.

**Comment by markmandel** [comment]
I think this can be closed now that https://github.com/googleforgames/quilkin/pull/543 has been implemented - the queues are now pretty much all gone.

Any objections?

**Comment by XAMPPRocky** [comment]
Nope, sounds good to me
