### ISSUE TITLE
Add admin endpoints to introspect proxy config

### ISSUE THREAD

**Issue by iffyio** [googleforgames/quilkin#394]
It would be very useful for operations to be able to be able to view the current config that a proxy is running at a given point in time.

Let's add two admin endpoints /clusters and /filterchain that returns a simplified JSON of the current cluster and filterchain respectively back to the caller. e.g:

```
$ curl quilkin:8080/clusters
[{
  "name": "default-cluster",
  "endpoints": [{
    "address": {
      "socketAddress": {
          "address": "127.0.0.1",
          "portValue": 1234
      }
    }
  }]
]}
```

```
$ curl quilkin:8080/filterchain
{
  "filters": [{
    {
      "name": "quilkin.extensions.filters.debug.v1alpha1.Debug",
      "config": {
        id: "hello"
      }  
    }  
  }]
}
```

**Comment by markmandel** [comment]
+1 on this! I think this is an excellent idea.

I know envoy also has a /config_dump option which gives back basically everything. Does it make more sense to start there and provide all the info, than each of the different filter options, like `/filterchain` ?

**Comment by iffyio** [comment]
That makes sense, alright the endpoint becomes /config_dump instead and would return something like:

```
$ curl quilkin:8080/config_dump
{
  "clusters": [{
    "name": "default-cluster",
    "endpoints": [{
        "address": "127.0.0.1",
        "port": 1234
    }]
  }],
  "filterchain": {
    "filters": [{
      {
        "name": "quilkin.extensions.filters.debug.v1alpha1.Debug",
        "config": {
          id: "hello"
        }  
      }  
    }]
  }
}

```
