### ISSUE TITLE
Limit LocalRateLimit per IP

### ISSUE THREAD

**Issue by tuongnd7** [googleforgames/quilkin#405]
I found LocalRateLimit to be working pretty well. 
However it only limits total packets, can you help me limit the number of packets per IP?
Thank you.

**Comment by iffyio** [comment]
The filter currently only rate limits for all packets as you mentioned. We have plans to have it [rate limit per ip](https://github.com/googleforgames/quilkin/issues/5#issuecomment-843808138) as well
