### ISSUE TITLE
Rename `Matches` to `Match`.

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#454]
`Match` could be a better name for the filter? think I remember a while ago @markmandel and I had discussed having a convention for filters and to use verbs like compress/encrypt where possible (not sure how well we've kept to it ^^)

_Originally posted by @iffyio in https://github.com/googleforgames/quilkin/pull/447#discussion_r759947759_

**Comment by markmandel** [comment]
I think Match would be better -does seem to be inline. We should probably document the standards for Filter names somewhere as well.

Did a quick playground test, and Rust doesn't complain about a `struct` called `Match`
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e757f0800bc897783e16a45eb813b344
