### ISSUE TITLE
Upgrade to Tokio 1.16.0

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#475]
As per: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.16.0

> Also, this release includes improvements to the multi-threaded scheduler that can increase throughput by up to 20% in some cases (#4383).

Seems like it would be worth doing the upgrade, and doing some benchmarking on before and after.

**Comment by XAMPPRocky** [comment]
I'll update it tomorrow
