### ISSUE TITLE
Docker image entrypoint should just be "/quilkin"

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#583]
**Is your feature request related to a problem? Please describe.**

Context:
https://github.com/googleforgames/quilkin/blob/0ba88ed2703cc85bb1bcbd3849cef9e0628c404f/image/Dockerfile#L23

Running Quilkin in xds provider mode requires you to replace the entire ENTRYPOINT, rather than altering arguments, since the entrypoint is setup to run only the proxy mode (which was the only mode at time of writing).

This is possible, but it is an extra point of friction, and it would be super nice if you didn't have to.

**Describe the solution you'd like**

```
ENTRYPOINT ["/quilkin"]
```

Then arguments could be provided for the container to specify what mode you wish to run in, which seems like the most amount of sense.

**Describe alternatives you've considered**

We could leave it as is, but it seems counter intuitive to how containers usually work 🤷🏻‍♂️

**Additional context**

* https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core - see "command"

There are various tests this would break, but they are all fixable.

**Comment by XAMPPRocky** [comment]
Yep, fully agree, I've already done that in my local branch.

**Comment by markmandel** [comment]
Making a note that we'd likely also need to update several pieces of documentation with this change as well.

**Comment by markmandel** [comment]
Working on this right now 👍🏻
