### ISSUE TITLE
Metrics having no data after refactors.

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#588]
**What happened**:

Some metrics don't seem to have data, which is odd:

![image](https://user-images.githubusercontent.com/298370/189498266-f59a6219-8213-4674-848f-471454530eef.png)

**What you expected to happen**:

See data received, and also packet processing time.

**How to reproduce it (as minimally and precisely as possible)**:

Install dashboards:
https://github.com/googleforgames/quilkin/tree/main/examples/grafana-dashboards

**Anything else we need to know?**:

When refactoring for port reuse, this may be the cause for breaking this.

**Environment**:
- Quilkin version: dev
- Execution environment (binary, container, etc): container
- Operating system: linux
- Custom filters? (Yes/No - if so, what do they do?): no
- Log(s): N/A
- Others: N/A

**Comment by XAMPPRocky** [comment]
I think it's just that those metrics have had slight name changes since that was added, so they just need to be updated
