### ISSUE TITLE
Multi-Cluster Support

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#600]
Now that we have Quilkin running as a xds management server, we want to extend that capability to multiple clusters, as currently it needs to run in the same cluster as where the gameservers are hosted where as we want to be able to place Quilkin at the edge in more regions than just the ones that contain gameservers.

To do this I'd like to propose a very simple addition to our current architecture. Which is the introduction of a kind of "relay" service that sits on-top of the management servers. Each management server would send a message to the relay to give its IP address, and then the relay server would initiate an xDS discovery stream with the management server, and then load balancers would connect to the relay service as a management server which would serve the aggregation of all the management servers.

Having the management servers initiate to relay to start the communication is important, because that allows the relay to serve N management servers dynamically as they pop up and shut down, the rest is just using the same xDS logic that we already have.

**Comment by markmandel** [comment]
I haven't gone deep on this, but could we use  https://github.com/envoyproxy/xds-relay ?
