### ISSUE TITLE
`quilkin_session_rx_bytes_total` metric seems to not be working

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#605]
I've noticed on the dashboard that this metric seems to not be working at all at them moment while `quilkin_session_tx_bytes_total` seems to be working just fine. Should investigate why, and add a test to prevent it from regressing.

**Comment by markmandel** [comment]
Ah yep - I saw this on the dashboard as well! I did wonder if was a dashboard issue or something else, but I hadn't gone back to have a look since #595 landed.

I wonder if I accidentally dropped it during #543
