### ISSUE TITLE
Print pod logs when steps fail in kubernetes integration tests

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#695]
Currently when the agones tests fail all you usually see is the `Elapsed` error. It would be nice if we added an error handler task to the agones integration, that whenever a task for a pod fails it outputs the logs from that pod, as well as the pod description, so that you can get a detailed overview of what went wrong in the test rather than just a "exceeded timeout".

**Comment by markmandel** [comment]
🤔 can you catch the panic on a failing Rust Test? I'd always assumed not. But yes, this would be extremely handy. Although with a panic handler you would need to go find the pods for that given test.

The other option is to have a utility "printPodLog(name: string)` function, that we can put in appropriate places. Would need to do things like manually check for equality first before doing the `assert` check, but that's perfectly doable.

**Comment by markmandel** [comment]
Another fun thought I just had. We could make a utility that puts a test specific unique label on each pod that a test creates, that way if a test fails, you could lookup all the pods that are being used for the test, and then grab all the logs and output them.

Oooh, I like this idea 😄

**Comment by XAMPPRocky** [comment]
> can you catch the panic on a failing Rust Test? I'd always assumed not

You can catch a panic, but we don't need to catch a panic because that's an error in the current process, rather than an error in the nodes, we just need to replace the `.unwrap()` on the timeouts with a error handler path that prints the logs I think.
