### ISSUE TITLE
The exponential backoff for k8s watch has no limit, the backoff can be months.

### ISSUE THREAD

**Issue by andersroos** [googleforgames/quilkin#731]
**What happened**:
During investigation of https://github.com/googleforgames/quilkin/issues/728 we noticed that the backoff for a failed k8s watch can be very long.

**What you expected to happen**:
That the watch should start again soon, probably within a few seconds, even on repeated errors.

**How to reproduce it (as minimally and precisely as possible)**:
Break the k8s resources as in https://github.com/googleforgames/quilkin/issues/728 and see the retry delay go up.

**Anything else we need to know?**:
The issue is that there is no max_dealy here: https://github.com/googleforgames/quilkin/blob/22b8ff8df68c695e8a6cb7e9e744f964d5eb6d7a/src/config/providers.rs#L73

On try number 25 the delay will be ~3 months. :-)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'll post a patch later today.
