### ISSUE TITLE
DualStackSocket's IPv6 mapped IPv4 address can break Maxmind integration

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#798]
A lot of maxmind databases such as ipnet don't have mappings for IPv6 mapped IPv4 addresses, so we should add logic to the lookup to check if it's a IPv6 mapped IPv4 address and then use the IPv4 version instead for the lookup.

**Comment by markmandel** [comment]
I did wonder if that might be the case, but wasn't sure.

With the maxmind integration - Is there a downside to trying the ipv6 lookup, and if it fails, then check to see if it's mapped, and if so, convert and ipv4 lookup?

That way if the db does support ipv6, it doesn't need to get converted? (I feel like I've seen some weird conversions that can happen in ipv6->ipv4 I didn't expect).

**Comment by XAMPPRocky** [comment]
> Is there a downside to trying the ipv6 lookup, and if it fails, then check to see if it's mapped, and if so, convert and ipv4 lookup?

The downside is that it's an additional lookup. But also I don't know if that would actually ever work, as these databases are based on CIDR. I think it would make more sense to check if it's a IPv4 mapped IPv6 address, and if it is, convert it and then lookup, as the check for the mapping and conversion is going to be cheaper than searching database twice.

**Comment by XAMPPRocky** [comment]
This one was fixed with the use of `to_canonical`.
