### ISSUE TITLE
Move project to Beta.

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#804]
Let's move the project to beta!

It's used in production, but we will probably still break a couple of APIs before we go to stable.

**Comment by markmandel** [comment]
@XAMPPRocky as part of this work, shall we also move all v1alpha1 items to v1beta1 as well?

https://github.com/search?q=repo%3Agoogleforgames%2Fquilkin%20alpha&type=code

I figure so, but just wondering if we still want to holdup the release for this 🤔 

Shouldn't be too hard, but figured I'd check.

**Comment by markmandel** [comment]
🤔 just an extra thought. Maybe just the Filter configs, move them to beta?

Since I think we still want to implement #700, maybe the config should stay as an alpha configuration?

Or do we wait on #700 before moving to beta 🤔

**Comment by XAMPPRocky** [comment]
> I figure so, but just wondering if we still want to holdup the release for this

Yes and no.

I think we should move those items, but I don't think we should holdup the release for it. It's better to release often than for it to be perfect. If we have frequent releases it removes the need for it to all be in one release. There's no reason why they all have to move on the same release, so if would hold up the release, I would leave it off.

**Comment by markmandel** [comment]
Sounds good. I'll taken off milestone.
