### ISSUE TITLE
ClusterMap::PartialEq is incredibly slow

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#857]
While doing #856 I added a benchmark for the ClusterMap::PartialEq implementation, and it shows it's _very_ slow. This is because it does a full equality check for every key and all endpoints. I suspect it could be made dramatically faster by computing a single hash for the endpoints that can be compared in the implementation instead since in many cases most of the endpoints for each key will not be different. 

Another option would be just a more clever way of doing change detection, because AFAICT the only reason for PartialEq is to satisfy `Watch<ClusterMap>`, and the current method of change detection is incredibly brute force, which is especially bad since eg. `handle_discovery_responses` will do this brute force change detection `n` times where `n` is how many `Cluster` resources there are in the protobuf. That should probably? be moved out to a single `.write()` regardless, but at least making change detection faster/better would improve that and other cases as well.

**Comment by XAMPPRocky** [comment]
> benchmark for the ClusterMap::PartialEq implementation, and it shows it's very slow.

Yep, 100% it is that was another thing I saw in the flame graphs.

> the current method of change detection is incredibly brute force

Absolutely it is was just the easiest way to allow for thread safe watchers of a type that interior mutability. If there's a better way to do it, we should pursue it.

**Comment by Jake-Shadle** [comment]
Only used by tests after #876
