### ISSUE TITLE
Look at replacing snappy with lz4

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#862]
This is a TODO to investigate switching from snappy to lz4 for compression. Generally speaking (obviously, variables like size of data, data patterns etc affect this) lz4 compresses relatively the same speed (but usually slight better ratio) than snappy, and tends to decompress _much_ faster than snappy.

**Comment by Jake-Shadle** [comment]
Or at least have it as an option to choose from.

**Comment by markmandel** [comment]
> Or at least have it as an option to choose from.

👍🏻

I tried to build this filter so it was extensible to allow for a variety of compression options - I figured being able to choose from a variety of compression would be useful, since it depends!
