### ISSUE TITLE
CI is very slow

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#865]
I've never used cloudbuild so I might be wrong about this, but the current CI build seems to be a sequential series of steps all executed on the same runner? If it's possible to parallelize execution of different steps it would drastically reduce the wall time of a single CI run which helps iteration and feedback, especially for things like building Mac which are more tedious if you aren't already using a Mac.

**Comment by markmandel** [comment]
There is some parallelisation ([see the `waitFor` commands](https://cloud.google.com/build/docs/configuring-builds/configure-build-step-order)), but in my experience - unit testing and building does tend to take up all cores of the CPU, so I left that part as sequential, as I figured it was diminishing returns at that point to try and do both tests and image building at the same time.
