### ISSUE TITLE
Add support for `--address-type` option to Agones agent

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#933]
To allow for more versatile address selection in the quilkin agent, we should add support for to allow for the users to specify which of the addresses quicken should use as the address for the gameserver.

### Steps
- Update the `GameServer` CRD to add support for `status.addresses`
- Add `--address-type` option to agones provider for agent, the option should accept a string as we can't assume that the types in address will be consistent.
- Add logic to the watch stream to select the address based on `--address-type` , this should be a case insensitive comparison. When there is multiple instances, we should choose the first one.

**Comment by markmandel** [comment]
Is `--address-type` the string key? (e.g. `PodIP`), or is it a ip version enum?

In theory there could be multiple `PodIP` keys in the `status.addresses`, one ipv4 and one ipv6 -- how do we want to disambiguate between address types as well?

**Comment by XAMPPRocky** [comment]
I guess I was thinking string, so I think we should probably add a second one for preferring multiple ones with different ip versions

**Comment by Jake-Shadle** [comment]
So initial dumb questions:

1. Does status.addresses replace status.address? Or are they complementary?
2. addresses is a map of <string> (what are some representative examples? is it truly open ended with no constraints?) -> <string> (is this the same as the current value of status.address?)? 
3. Presumably `endpoint()` takes in the address type now?
