### ISSUE TITLE
io_uring threads can get into high CPU condition

### ISSUE THREAD

**Issue by AndrewGambell** [googleforgames/quilkin#952]
**What happened**:

During testing with a modest amount of concurrent user sessions (flows) 200+ followed by a period of inactivity some io_uring threads will go to 100% CPU. The increased number of user session results in a greater likely hood to get into the high CPU state.

The profiler shows we are spending a lot of time writing metrics, but this seems to be because the downstream channel is closed and we are return None straight away in this code block.

https://github.com/googleforgames/quilkin/blob/0f1f5bc60bdec2482b204dd0b6e1cf0b424e0e85/src/components/proxy/sessions.rs#L132

We also see a huge amount of "downstream channel closed" incrementing errors

```
quilkin_errors_total{asn="",display="downstream channel closed",event="write",ip_prefix=""} 12203441006
```

<img width="1638" alt="image" src="https://github.com/googleforgames/quilkin/assets/54988988/6b38792f-b8af-451e-b1b9-25957bda5380">

**How to reproduce it (as minimally and precisely as possible)**:

Using fortio you can pretty reliably get into the fault condition 

- 400 qps, 200 threads for 20s
- Wait 60s for sessions to clear
- 400 qps, 200 threads for 20s

top will show io_uring thread at 100%

Bumping fortio to 10000 qps and 10000 threads, results in a large amount of threads going high CPU.

**Anything else we need to know?**:

Basic configuration was used to replicate this.

```
version: v1alpha1
id: my-proxy
clusters:
  - endpoints:
    - address: 10.9.16.5:8078
```

**Environment**:
- Quilkin version: 0.8.0 and 1556b190de24d6b3f67e27b19792a1ff82d22a16
- Execution environment (binary, container, etc): binary and container
- Operating system: Linux  Kernel 6.1.53 and 6.6.16
- Custom filters? (Yes/No - if so, what do they do?):
- Log(s):
- Others:

**Comment by AndrewGambell** [comment]
interestingly adding a return after the metric increment seems stop it going high CPU, which seems to follow the pattern in the socket closing code on line 186 of the same block. I'm struggling a little to follow the code past that at the moment.

https://github.com/googleforgames/quilkin/blob/0f1f5bc60bdec2482b204dd0b6e1cf0b424e0e85/src/components/proxy/sessions.rs#L132
```
             uring_inner_spawn!(async move {
                loop {
                    match downstream_receiver.recv().await {
                        None => {
                            crate::metrics::errors_total(
                                crate::metrics::WRITE,
                                "downstream channel closed",
                                None,
                            )
                            .inc();
                            return;
                        }
```

**Comment by markmandel** [comment]
Looking at the code, and reviewing https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html I think you hit the nail on the had @AndrewGambell .

> Similarly, if Sender is disconnected while trying to recv, the recv method will return None.

So when the `downstream_receiver` is closed, without the `return` that you found the code enters an infinite `loop`, which will return `None` every time it comes around to the `downstream_receiver.recv().await` operation.

**Comment by AndrewGambell** [comment]
While we should probably return there so we are not in a hard loop. 

I'm not sure why the channel gets into that state to begin with, and in a somewhat inconsistent manner. There seems to be some sort of race condition that leads to the channel being closed during the session tear down process?
