### ISSUE TITLE
Changes To The ConfigMap in the Relay aren't being picked up by proxies

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#960]
We've noticed that changing the configmap of filters in the relay doesn't seem to properly update the proxies configuration, like it should.

**Comment by markmandel** [comment]
This may well be due to: https://ahmet.im/blog/kubernetes-inotify/

**Comment by XAMPPRocky** [comment]
We don't mount the configmap as a file though, we discover and watch the map through the k8s API.

**Comment by markmandel** [comment]
oh yeah! Good point. Okay, yeah that is weird.
