### ISSUE TITLE
0.9.0 Release

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#964]
I was holding off on setting up the 0.9.0 release, since there were several critical bug fixes in the pipeline.

Looks like that's all sorted now, so just checking if there's anything I should block on before kicking off this release?

**Comment by XAMPPRocky** [comment]
No, kick it off :)

**Comment by markmandel** [comment]
Only thought I have - do we care that we don't have docs for `HashedTokenRouter`  in [our guides](https://googleforgames.github.io/quilkin/main/book/services/proxy/filters/token_router.html)? Or is that more of an experiment that may eventually end up being the TokenRouter? In which case, better to leave it undocumented until testing is complete. I wasn't quite sure.

**Comment by markmandel** [comment]
@Jake-Shadle with #965 merged, https://googleforgames.github.io/quilkin/main/book/services/xds.html#supported-apis is now out of date, yes?

Tracking documentation changes that will need to be made before a release can be cut.

**Comment by markmandel** [comment]
Now https://github.com/googleforgames/quilkin/pull/980 is merged, just waiting on #970 doc updates.

**Comment by markmandel** [comment]
Need these two implemented/merged before release. Everthing above is done/obsolete.

* [ ] https://github.com/googleforgames/quilkin/pull/982
* [ ] https://github.com/googleforgames/quilkin/issues/983

**Comment by markmandel** [comment]
Okay, we have everything that was blocking release merged now! Any final objections before I kick this off @XAMPPRocky @Jake-Shadle ?

**Comment by XAMPPRocky** [comment]
Nope

**Comment by Jake-Shadle** [comment]
No

**Comment by markmandel** [comment]
# Release 0.9.0

## Prerequisites

- [ ] Have at least `Editor` level access to `quilkin` Google Cloud project.
- [ ] Local gcloud configuration is pointing at the `quilkin` Google Cloud project. 
- [ ] Local git remote `upstream` points at `git@github.com:googleforgames/quilkin.git`.

## Steps

- [ ] Review that closed issues have appropriate tags for the changelog.
- [ ] Review that merged PRs have appropriate tags for the changelog.
- [ ] Run `git remote update && git checkout main && git reset --hard upstream/main` to ensure your code is in line
  with upstream.
- [ ] Update Cargo version for release
    - [ ] Edit the `version` field in `./Cargo.toml` and remove the `-dev` suffix.
    - [ ] Edit the `quilkin-macros` dependency in `./Cargo.toml` and remove the `-dev` suffix.
    - [ ] Edit the `version` field in `./macros/Cargo.toml` and remove the `-dev` suffix.
- [ ] cd to `./build/release` and run `make` to submit the cloud build
- [ ] Download all the artifacts from the cloud build.
- [ ] Review `license.html` to ensure that there aren't any new MPL, or CDDL dependencies from the last 
  release. If there are:
    - [ ] Add the dependencies to [archive_dependencies.sh](https://github.com/googleforgames/quilkin/blob/main/build/release/archive_dependencies.sh)
          so that the source is archived in the container image.
    - [ ] Reset checklist back to "run `make` to submit the cloud build", and start from there again.
- [ ] Run `cd macros && cargo publish --dry-run --allow-dirty` and ensure there are no issues.
- [ ] Run `cargo clippy` in the root directory, and ensure there are no issues.
- [ ] Add a release item to README.md "Documentation" > "Releases" list with related links in reverse chronological 
  order.
- [ ] Review any `data-proofer-ignore` attributes from links in the documentation in `./docs`, and remove any no 
  longer needed.
- [ ] Create a draft [Github release](https://github.com/googleforgames/quilkin/releases/new)
    - [ ] Populate the tag with `v0.9.0`
    - [ ] Click `Generate release notes` to generate the change log for this release.
    - [ ] Copy the release notes from the draft release and paste it at the top of CHANGELOG.md. 
    - [ ] Using the
      [Github release template](https://github.com/googleforgames/quilkin/blob/main/build/templates/github-release.md)
      update the generated release notes with a description, and relevant changelog sections.
    - [ ] Attach all the cloud build artifacts to the draft GitHub release.
- [ ] Submit these changes as a PR, and merge with approval.
- [ ] Run `git remote update && git checkout main && git reset --hard upstream/main` to ensure your code is in line
      with upstream.
- [ ] Run `git checkout -b release-0.9.0 && git push upstream release-0.9.0` to create a release branch.
- [ ] Publish to [crates.io/crates/quilkin-macros](https://crates.io/crates/quilkin-macros): run `cd macros && cargo publish`
- [ ] Publish to [crates.io/crates/quilkin](https://crates.io/crates/quilkin): run `cargo publish`
- [ ] Submit the release.
- [ ] Post announcemnts
  - [ ] [mailing list](https://groups.google.com/g/quilkin-discuss).
  - [ ] [Discord #announcement](https://discord.com/channels/773975408265134100/879794098721140786) 
  - [ ] [Twitter account](https://twitter.com/quilkindev).
- [ ] Update Cargo version for development
    - [ ] Edit `Cargo.toml` and increment the [minor version](https://semver.org/) and apply the `-dev` suffix to the
       `version`.
    - [ ] Edit the `quilkin-macros` dependency in `./Cargo.toml` and increment the [minor version](https://semver.org/) 
       and apply the `-dev` suffix to the `version`.
    - [ ] Edit the `version` field in `./macros/Cargo.toml`and increment the [minor version](https://semver.org/)
       and apply the `-dev` suffix to the `version`.
- [ ] Submit this change as a PR, and merge with approval.

Congratulation! 🎉 You have successfully released Quilkin!
