### ISSUE TITLE
Add heap profiling

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#984]
Related to #983, we should add heap profiling/tracking to quilkin as an additional source of runtime information to the existing pprof data. This could be optional as well either at build or runtime.

I think it would be useful to also use something like https://github.com/nnethercote/dhat-rs in at least one test when reproing #983 so that we have continuous testing of the memory usage so that whatever the fix/es is/are for #983 don't regress.

**Comment by XAMPPRocky** [comment]
Similar to pprof, it would be good if we can integrate this in a pyroscope compatible format so that we can see it in production.

There is https://docs.rs/pyroscope/ but I'm not sure if that includes memory profiling or not.
